// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qhwpdfvhmkrreqndnogm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFod3BkZnZobWtycmVxbmRub2dtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNzgyOTAsImV4cCI6MjA2ODY1NDI5MH0.Z_XpX2Dtm7WuDVL1mEb-syR_phmZZB4NYFQvCQSIliI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});